export default {
  4101: 'Information Incomplete',
  4102: 'Name must be unique',
  4103: 'Email or password are incorrect',
  4104: 'Not found',
  4105: 'El email no ha sido verificado',
  4106: 'Te registraste a través de redes sociales',
  4107: 'Token not found',
  4108: 'Invalid or expired token',
  4109: 'Token incorrecto o fuera de propósito',
  4110: 'Este email ya ha sido verificado',
  4111: 'La información de login es incorrecta',
  4112: 'Datos mal solicitados en el perfil de social media',
  4114: 'No tienes permisos para acceder',
  4115: 'Falta información o permisos para acceder a la información',
  4116: 'Id de objeto inválido',
  4117: 'Archivo inválido',
  4118: 'Las referencias dentro del objeto son inválidas o no existen',
  4120: 'La eliminación de este recurso creará conflictos',
  4121: 'Ocurrió un error al momento de subir los archivos',
  500: 'Error Services',
};
