module.exports = {
  // 4101 Joi validation error
  4102: 'Field must be unique',
  4103: 'Wrong credentials',
  4104: 'Not found',
  4105: 'Email not verified',
  4106: 'Different sign up method',
  4107: 'Access denied. No token provided.',
  4108: 'Invalid or expired token',
  4109: 'Incorrect token purpose',
  4110: 'Email already verified',
  4111: 'Name already exists',
  4112: 'Wrong scope options for social profile',
  4113: 'App version requires update',
  4114: 'User not authorized',
  4115: 'Request headers are missing or incorrect',
  4116: 'Invalid Object Id',
  4117: 'Invalid File',
  4118: 'References are invalid or non existent',
  4119: 'Prerequisites to process request are incomplete',
  4120: 'Attempting to delete a necessary item',
  4121: 'User options could not be retrieved',
  4122: 'No payment found or insufficient credits for subscription',
  4123: 'Resource is at its full capacity',
};
